force-app/main/default/objects/Slot__c/Slot__c.object-meta.xml
<CustomObject>
    <fullName>Slot__c</fullName>
    <label>Slot</label>
    <pluralLabel>Slots</pluralLabel>
    <nameField>
        <label>Slot Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>

   
    <fields>
        <fullName>Practitioner__c</fullName>
        <label>Practitioner</label>
        <type>Lookup</type>
        <referenceTo>User</referenceTo> 
        <relationshipName>PractitionerSlots</relationshipName>
    </fields>

    <fields>
        <fullName>Start__c</fullName>
        <label>Start Time</label>
        <type>DateTime</type>
    </fields>

    <fields>
        <fullName>End__c</fullName>
        <label>End Time</label>
        <type>DateTime</type>
    </fields>

    <fields>
        <fullName>IsBlocked__c</fullName>
        <label>Is Blocked</label>
        <type>Checkbox</type>
        <defaultValue>false</defaultValue>
    </fields>

    <fields>
        <fullName>Capacity__c</fullName>
        <label>Capacity</label>
        <type>Number</type>
        <precision>2</precision>
        <scale>0</scale>
    </fields>

    <fields>
        <fullName>Reason__c</fullName>
        <label>Reason</label>
        <type>Text</type>
        <length>255</length>
    </fields>

    <fields>
        <fullName>Timezone__c</fullName>
        <label>Timezone</label>
        <type>Text</type>
        <length>50</length>
    </fields>

    <fields>
        <fullName>Availability__c</fullName>
        <label>Availability</label>
        <type>Lookup</type>
        <referenceTo>Availability__c</referenceTo>
        <relationshipName>SlotAvailability</relationshipName>
    </fields>

</CustomObject>

force-app/main/default/objects/Slot__c/fields/IsBlocked__c.field-meta.xml
<CustomField>
    <fullName>IsBlocked__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Blocked</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Slot__c/fields/Practitioner__c.field-meta.xml
<CustomField>
    <fullName>Practitioner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Practitioner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>PractitionerSlots</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Slot__c/fields/Start__c.field-meta.xml
<CustomField>
    <fullName>Start__c</fullName>
    <label>Start Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/TelemedicineController.cls
/**
 * @description Controller for Lightning Web Components (LWC) handling the telemedicine UI logic.
 * Exposes data to the frontend, allowing patients to view available slots.
 * @author AK
 */
public with sharing class TelemedicineController {
    
    /**
     * @description Retrieves a list of future, unblocked time slots for a specific practitioner.
     * Marked as cacheable=true for optimal performance in LWC.
     * @param practitionerId The ID of the doctor
     * @return List of available Slot__c records sorted by time
     */
    @AuraEnabled(cacheable=true)
    public static List<Slot__c> getAvailableSlots(Id practitionerId) {
        return [
            SELECT Id, Start__c, End__c, Practitioner__r.Name 
            FROM Slot__c 
            WHERE Practitioner__c = :practitionerId 
            AND IsBlocked__c = false
            AND Start__c >= :DateTime.now()
            ORDER BY Start__c ASC
        ];
    }
}